workflows:
  android-build:
    name: Android Build
    max_build_duration: 200
    environment:
      vars:
        GRADLE_TASK: "assembleDebug"
      android:
        image: android-latest
      java:
        version: jdk11
    scripts:
      - echo "Starting the build process..."
      - chmod +x ./gradlew
      - ./gradlew clean $GRADLE_TASK
artifacts:
  - build/**/*.apk
publishing:
  email:
    recipients:
      - "kavinithees2696@gmail.com"